spring:
  application:
    title: Cakk
    version: 1.0.0
  banner:
    location: classpath:/app-banner.dat
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

storage:
  datasource:
    core:
      jdbc-url: jdbc:mysql://localhost:3306/cakk
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      data-source-properties:
        rewriteBatchedStatements: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

oauth:
  kakao:
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json
  apple:
    public-key-url: https://appleid.apple.com/auth/keys
  google:
    client-id: ${GOOGLE_CLIENT_ID}

jwt:
  access-header: Authorization
  refresh-header: Refresh
  grant-type: Bearer
  user-key: USER
