server:
  servlet:
    context-path: /api/v1

spring:
  application:
    title: Cakk
    version: 1.0.0
  banner:
    location: classpath:/app-banner.dat
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  access-header: Authorization
  refresh-header: Refresh
  grant-type: Bearer
  user-key: USER
