spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

storage:
  datasource:
    core:
      jdbc-url: jdbc:mysql://localhost:3306/cakk
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      data-source-properties:
        rewriteBatchedStatements: true

oauth:
  kakao:
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json
  apple:
    public-key-url: https://appleid.apple.com/auth/keys
  google:
    client-id: ${GOOGLE_CLIENT_ID}

jwt:
  secret: localocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocal
  expiration:
    access-token: 1814400000
    refresh-token: 2592000000

slack:
  webhook:
    is-enable: false
    url: url

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    s3:
      bucket: test-bucket
      expire-in: 180000
      object-key: key
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false
