jwt:
  secret: localocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocalocal
  expiration:
    access-token: 1814400000
    refresh-token: 2592000000

slack:
  webhook:
    is-enable: false
    url: url

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    s3:
      bucket: test-bucket
      expire-in: 180000
      object-key: key
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false