spring:
  application:
    title: Cakk-Batch
    version: 1.0.0
  banner:
    location: classpath:/batch-banner.dat
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
      name: ${job.name:NONE}
