version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: cakk-redis
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/volumes/redis/_data:/data
      - /var/lib/docker/volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf