version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: cakk-redis
    ports:
      - {port:6379}
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf
